/**
 * Configuración optimizada de Lighthouse para el proyecto filter-docs
 *
 * Esta configuración está optimizada para:
 * - Análisis más rápido y eficiente
 * - Mejor cobertura de auditorías
 * - Configuraciones específicas para React/Vite
 * - Soporte para desarrollo y producción
 */

export default {
  // Configuración básica
  extends: 'lighthouse:default',

  // Configuración del navegador
  settings: {
    // Configuración para móvil (recomendado por Google)
    formFactor: 'mobile',

    // Throttling optimizado para conexiones reales
    throttling: {
      // Simular conexión 4G rápida
      rttMs: 20,
      throughputKbps: 20480,
      cpuSlowdownMultiplier: 1,
      requestLatencyMs: 0,
      downloadThroughputKbps: 0,
      uploadThroughputKbps: 0,
    },

    // Configuración de pantalla moderna
    screenEmulation: {
      mobile: true,
      width: 390, // iPhone 12/13/14
      height: 844,
      deviceScaleFactor: 3,
      disabled: false,
    },

    // User agent moderno
    emulatedUserAgent:
      'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',

    // Configuraciones adicionales para mejor rendimiento
    maxWaitForLoad: 45000, // 45 segundos máximo
    disableFullPageScreenshot: false,
    skipAudits: [
      // Auditorías que pueden ser problemáticas en desarrollo
      'uses-http2', // No aplicable en localhost
      'uses-long-cache-ttl', // No aplicable en desarrollo
      'redirects-http', // No aplicable en localhost
    ],

    // Configuración para análisis más rápido
    onlyCategories: ['performance', 'accessibility', 'best-practices', 'seo'],

    // Configuración específica para React/Vite
    chromeFlags: [
      '--headless',
      '--no-sandbox',
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-web-security',
      '--disable-features=VizDisplayCompositor',
    ],
  },

  // Configuración de auditorías específicas
  audits: [
    // Auditorías de rendimiento críticas
    'first-contentful-paint',
    'largest-contentful-paint',
    'first-meaningful-paint',
    'speed-index',
    'cumulative-layout-shift',
    'total-blocking-time',
    'max-potential-fid',
    'interactive',

    // Auditorías de recursos
    'server-response-time',
    'render-blocking-resources',
    'unused-css-rules',
    'unused-javascript',
    'modern-image-formats',
    'uses-optimized-images',
    'uses-text-compression',
    'uses-responsive-images',
    'efficient-animated-content',
    'preload-lcp-image',
    'total-byte-weight',
    'dom-size',
    'critical-request-chains',
    'user-timings',
    'bootup-time',
    'mainthread-work-breakdown',
    'font-display',
    'resource-summary',
    'third-party-summary',
    'largest-contentful-paint-element',
    'layout-shift-elements',
    'long-tasks',
    'non-composited-animations',
    'unsized-images',

    // Auditorías de accesibilidad
    'accesskeys',
    'aria-allowed-attr',
    'aria-allowed-role',
    'aria-command-name',
    'aria-conditional-attr',
    'aria-deprecated-role',
    'aria-dialog-name',
    'aria-hidden-body',
    'aria-hidden-focus',
    'aria-input-field-name',
    'aria-meter-name',
    'aria-progressbar-name',
    'aria-prohibited-attr',
    'aria-required-attr',
    'aria-required-children',
    'aria-required-parent',
    'aria-roles',
    'aria-text',
    'aria-toggle-field-name',
    'aria-tooltip-name',
    'aria-treeitem-name',
    'aria-valid-attr-value',
    'aria-valid-attr',
    'button-name',
    'bypass',
    'color-contrast',
    'definition-list',
    'dlitem',
    'document-title',
    'duplicate-id-aria',
    'empty-heading',
    'form-field-multiple-labels',
    'frame-title',
    'heading-order',
    'html-has-lang',
    'html-lang-valid',
    'html-xml-lang-mismatch',
    'identical-links-same-purpose',
    'image-alt',
    'image-redundant-alt',
    'input-button-name',
    'input-image-alt',
    'label-content-name-mismatch',
    'label',
    'landmark-one-main',
    'link-name',
    'link-in-text-block',
    'list',
    'listitem',
    'meta-refresh',
    'meta-viewport',
    'object-alt',
    'select-name',
    'skip-link',
    'tabindex',
    'table-duplicate-name',
    'table-fake-caption',
    'target-size',
    'td-has-header',
    'td-headers-attr',
    'th-has-data-cells',
    'valid-lang',
    'video-caption',
    'custom-controls-labels',
    'custom-controls-roles',
    'focus-traps',
    'focusable-controls',
    'interactive-element-affordance',
    'logical-tab-order',
    'managed-focus',
    'offscreen-content-hidden',
    'use-landmarks',
    'visual-order-follows-dom',

    // Auditorías de mejores prácticas
    'is-on-https',
    'redirects-http',
    'viewport',
    'errors-in-console',
    'server-response-time',
    'interactive',
    'user-timings',
    'critical-request-chains',
    'redirects',
    'image-aspect-ratio',
    'image-size-responsive',
    'deprecations',
    'third-party-cookies',
    'mainthread-work-breakdown',
    'bootup-time',
    'uses-rel-preconnect',
    'font-display',
    'diagnostics',
    'network-requests',
    'network-rtt',
    'network-server-latency',
    'main-thread-tasks',
    'metrics',
    'resource-summary',
    'third-party-summary',
    'third-party-facades',
    'largest-contentful-paint-element',
    'lcp-lazy-loaded',
    'layout-shifts',
    'long-tasks',
    'non-composited-animations',
    'unsized-images',
    'valid-source-maps',
    'prioritize-lcp-image',
    'csp-xss',
    'has-hsts',
    'origin-isolation',
    'clickjacking-mitigation',
    'trusted-types-xss',
    'script-treemap-data',

    // Auditorías de SEO
    'meta-description',
    'http-status-code',
    'font-size',
    'link-text',
    'crawlable-anchors',
    'is-crawlable',
    'robots-txt',
    'hreflang',
    'canonical',
    'structured-data',
    'bf-cache',
    'cache-insight',
    'cls-culprits-insight',
    'document-latency-insight',
    'dom-size-insight',
    'duplicated-javascript-insight',
    'font-display-insight',
    'forced-reflow-insight',
    'image-delivery-insight',
    'inp-breakdown-insight',
    'lcp-breakdown-insight',
    'lcp-discovery-insight',
    'legacy-javascript-insight',
    'modern-http-insight',
    'network-dependency-tree-insight',
    'render-blocking-insight',
    'third-parties-insight',
    'viewport-insight',
  ],

  // Configuración de categorías optimizada
  categories: {
    performance: {
      title: 'Performance',
      description:
        'These metrics encapsulate the user experience of loading and interacting with the page.',
      auditRefs: [
        // Core Web Vitals (máxima prioridad)
        { id: 'largest-contentful-paint', weight: 25, group: 'metrics' },
        { id: 'total-blocking-time', weight: 30, group: 'metrics' },
        { id: 'cumulative-layout-shift', weight: 15, group: 'metrics' },

        // Métricas adicionales
        { id: 'first-contentful-paint', weight: 10, group: 'metrics' },
        { id: 'first-meaningful-paint', weight: 7, group: 'metrics' },
        { id: 'speed-index', weight: 10, group: 'metrics' },
        { id: 'max-potential-fid', weight: 10, group: 'metrics' },
        { id: 'interactive', weight: 5, group: 'metrics' },

        // Diagnósticos
        { id: 'server-response-time', weight: 10, group: 'diagnostics' },
        { id: 'render-blocking-resources', weight: 10, group: 'diagnostics' },
        { id: 'unused-css-rules', weight: 2, group: 'diagnostics' },
        { id: 'unused-javascript', weight: 2, group: 'diagnostics' },
        { id: 'total-byte-weight', weight: 1, group: 'diagnostics' },
        { id: 'dom-size', weight: 1, group: 'diagnostics' },
        { id: 'critical-request-chains', weight: 1, group: 'diagnostics' },
        { id: 'user-timings', weight: 1, group: 'diagnostics' },
        { id: 'bootup-time', weight: 1, group: 'diagnostics' },
        { id: 'mainthread-work-breakdown', weight: 1, group: 'diagnostics' },
        { id: 'resource-summary', weight: 1, group: 'diagnostics' },
        { id: 'third-party-summary', weight: 1, group: 'diagnostics' },
        {
          id: 'largest-contentful-paint-element',
          weight: 1,
          group: 'diagnostics',
        },
        { id: 'layout-shift-elements', weight: 1, group: 'diagnostics' },
        { id: 'long-tasks', weight: 1, group: 'diagnostics' },

        // Oportunidades
        { id: 'modern-image-formats', weight: 1, group: 'opportunities' },
        { id: 'uses-optimized-images', weight: 1, group: 'opportunities' },
        { id: 'uses-text-compression', weight: 1, group: 'opportunities' },
        { id: 'uses-responsive-images', weight: 1, group: 'opportunities' },
        { id: 'efficient-animated-content', weight: 1, group: 'opportunities' },
        { id: 'preload-lcp-image', weight: 1, group: 'opportunities' },
        { id: 'font-display', weight: 1, group: 'opportunities' },
        { id: 'non-composited-animations', weight: 1, group: 'opportunities' },
        { id: 'unsized-images', weight: 1, group: 'opportunities' },
      ],
    },

    accessibility: {
      title: 'Accessibility',
      description:
        'These checks highlight opportunities to improve the accessibility of your web app.',
      auditRefs: [
        { id: 'color-contrast', weight: 10, group: 'a11y-color-contrast' },
        { id: 'image-alt', weight: 8, group: 'a11y-names-labels' },
        { id: 'label', weight: 8, group: 'a11y-names-labels' },
        { id: 'link-name', weight: 8, group: 'a11y-names-labels' },
        { id: 'button-name', weight: 8, group: 'a11y-names-labels' },
        { id: 'document-title', weight: 7, group: 'a11y-names-labels' },
        { id: 'html-has-lang', weight: 7, group: 'a11y-language' },
        { id: 'meta-viewport', weight: 6, group: 'a11y-navigation' },
        { id: 'target-size', weight: 6, group: 'a11y-navigation' },
        { id: 'list', weight: 5, group: 'a11y-structure-semantics' },
        { id: 'listitem', weight: 5, group: 'a11y-structure-semantics' },
        { id: 'heading-order', weight: 5, group: 'a11y-structure-semantics' },
        {
          id: 'landmark-one-main',
          weight: 5,
          group: 'a11y-structure-semantics',
        },
        { id: 'skip-link', weight: 4, group: 'a11y-navigation' },
        { id: 'aria-allowed-attr', weight: 4, group: 'a11y-aria' },
        { id: 'aria-allowed-role', weight: 4, group: 'a11y-aria' },
        { id: 'aria-required-attr', weight: 4, group: 'a11y-aria' },
        { id: 'aria-required-children', weight: 4, group: 'a11y-aria' },
        { id: 'aria-required-parent', weight: 4, group: 'a11y-aria' },
        { id: 'aria-roles', weight: 4, group: 'a11y-aria' },
        { id: 'aria-valid-attr', weight: 4, group: 'a11y-aria' },
        { id: 'aria-valid-attr-value', weight: 4, group: 'a11y-aria' },
        { id: 'aria-hidden-body', weight: 3, group: 'a11y-aria' },
        { id: 'aria-hidden-focus', weight: 3, group: 'a11y-aria' },
        { id: 'aria-input-field-name', weight: 3, group: 'a11y-aria' },
        { id: 'aria-progressbar-name', weight: 3, group: 'a11y-aria' },
        { id: 'aria-toggle-field-name', weight: 3, group: 'a11y-aria' },
        { id: 'aria-tooltip-name', weight: 3, group: 'a11y-aria' },
        { id: 'aria-treeitem-name', weight: 3, group: 'a11y-aria' },
        { id: 'aria-command-name', weight: 2, group: 'a11y-aria' },
        { id: 'aria-dialog-name', weight: 2, group: 'a11y-aria' },
        { id: 'aria-meter-name', weight: 2, group: 'a11y-aria' },
        { id: 'aria-conditional-attr', weight: 2, group: 'a11y-aria' },
        { id: 'aria-deprecated-role', weight: 2, group: 'a11y-aria' },
        { id: 'aria-prohibited-attr', weight: 2, group: 'a11y-aria' },
        { id: 'aria-text', weight: 2, group: 'a11y-aria' },
        { id: 'bypass', weight: 2, group: 'a11y-navigation' },
        { id: 'definition-list', weight: 2, group: 'a11y-structure-semantics' },
        { id: 'dlitem', weight: 2, group: 'a11y-structure-semantics' },
        { id: 'duplicate-id-aria', weight: 2, group: 'a11y-aria' },
        { id: 'empty-heading', weight: 2, group: 'a11y-structure-semantics' },
        {
          id: 'form-field-multiple-labels',
          weight: 2,
          group: 'a11y-names-labels',
        },
        { id: 'frame-title', weight: 2, group: 'a11y-names-labels' },
        { id: 'html-lang-valid', weight: 2, group: 'a11y-language' },
        { id: 'html-xml-lang-mismatch', weight: 2, group: 'a11y-language' },
        {
          id: 'identical-links-same-purpose',
          weight: 2,
          group: 'a11y-names-labels',
        },
        { id: 'image-redundant-alt', weight: 2, group: 'a11y-names-labels' },
        { id: 'input-button-name', weight: 2, group: 'a11y-names-labels' },
        { id: 'input-image-alt', weight: 2, group: 'a11y-names-labels' },
        {
          id: 'label-content-name-mismatch',
          weight: 2,
          group: 'a11y-names-labels',
        },
        { id: 'link-in-text-block', weight: 2, group: 'a11y-color-contrast' },
        { id: 'meta-refresh', weight: 2, group: 'a11y-navigation' },
        { id: 'object-alt', weight: 2, group: 'a11y-names-labels' },
        { id: 'select-name', weight: 2, group: 'a11y-names-labels' },
        { id: 'tabindex', weight: 2, group: 'a11y-navigation' },
        {
          id: 'table-duplicate-name',
          weight: 2,
          group: 'a11y-structure-semantics',
        },
        {
          id: 'table-fake-caption',
          weight: 2,
          group: 'a11y-structure-semantics',
        },
        { id: 'td-has-header', weight: 2, group: 'a11y-structure-semantics' },
        { id: 'td-headers-attr', weight: 2, group: 'a11y-structure-semantics' },
        {
          id: 'th-has-data-cells',
          weight: 2,
          group: 'a11y-structure-semantics',
        },
        { id: 'valid-lang', weight: 2, group: 'a11y-language' },
        { id: 'video-caption', weight: 2, group: 'a11y-media' },
        { id: 'custom-controls-labels', weight: 1, group: 'a11y-names-labels' },
        { id: 'custom-controls-roles', weight: 1, group: 'a11y-aria' },
        { id: 'focus-traps', weight: 1, group: 'a11y-navigation' },
        { id: 'focusable-controls', weight: 1, group: 'a11y-navigation' },
        {
          id: 'interactive-element-affordance',
          weight: 1,
          group: 'a11y-navigation',
        },
        { id: 'logical-tab-order', weight: 1, group: 'a11y-navigation' },
        { id: 'managed-focus', weight: 1, group: 'a11y-navigation' },
        { id: 'offscreen-content-hidden', weight: 1, group: 'a11y-navigation' },
        { id: 'use-landmarks', weight: 1, group: 'a11y-structure-semantics' },
        { id: 'visual-order-follows-dom', weight: 1, group: 'a11y-navigation' },
      ],
    },

    'best-practices': {
      title: 'Best Practices',
      description:
        "We've compiled some recommendations to help your site follow web development best practices.",
      auditRefs: [
        { id: 'is-on-https', weight: 10, group: 'best-practices-trust-safety' },
        {
          id: 'redirects-http',
          weight: 10,
          group: 'best-practices-trust-safety',
        },
        { id: 'viewport', weight: 10, group: 'best-practices-user-experience' },
        {
          id: 'errors-in-console',
          weight: 8,
          group: 'best-practices-trust-safety',
        },
        {
          id: 'image-aspect-ratio',
          weight: 8,
          group: 'best-practices-user-experience',
        },
        {
          id: 'image-size-responsive',
          weight: 8,
          group: 'best-practices-user-experience',
        },
        { id: 'deprecations', weight: 7, group: 'best-practices-trust-safety' },
        {
          id: 'third-party-cookies',
          weight: 7,
          group: 'best-practices-trust-safety',
        },
        {
          id: 'mainthread-work-breakdown',
          weight: 6,
          group: 'best-practices-performance',
        },
        { id: 'bootup-time', weight: 6, group: 'best-practices-performance' },
        {
          id: 'uses-rel-preconnect',
          weight: 6,
          group: 'best-practices-performance',
        },
        { id: 'font-display', weight: 6, group: 'best-practices-performance' },
        { id: 'diagnostics', weight: 5, group: 'best-practices-performance' },
        {
          id: 'network-requests',
          weight: 5,
          group: 'best-practices-performance',
        },
        { id: 'network-rtt', weight: 5, group: 'best-practices-performance' },
        {
          id: 'network-server-latency',
          weight: 5,
          group: 'best-practices-performance',
        },
        {
          id: 'main-thread-tasks',
          weight: 5,
          group: 'best-practices-performance',
        },
        { id: 'metrics', weight: 5, group: 'best-practices-performance' },
        {
          id: 'resource-summary',
          weight: 5,
          group: 'best-practices-performance',
        },
        {
          id: 'third-party-summary',
          weight: 5,
          group: 'best-practices-performance',
        },
        {
          id: 'third-party-facades',
          weight: 5,
          group: 'best-practices-performance',
        },
        {
          id: 'largest-contentful-paint-element',
          weight: 4,
          group: 'best-practices-performance',
        },
        {
          id: 'lcp-lazy-loaded',
          weight: 4,
          group: 'best-practices-performance',
        },
        { id: 'layout-shifts', weight: 4, group: 'best-practices-performance' },
        { id: 'long-tasks', weight: 4, group: 'best-practices-performance' },
        {
          id: 'non-composited-animations',
          weight: 4,
          group: 'best-practices-performance',
        },
        {
          id: 'unsized-images',
          weight: 4,
          group: 'best-practices-performance',
        },
        {
          id: 'valid-source-maps',
          weight: 4,
          group: 'best-practices-trust-safety',
        },
        {
          id: 'prioritize-lcp-image',
          weight: 4,
          group: 'best-practices-performance',
        },
        { id: 'csp-xss', weight: 3, group: 'best-practices-trust-safety' },
        { id: 'has-hsts', weight: 3, group: 'best-practices-trust-safety' },
        {
          id: 'origin-isolation',
          weight: 3,
          group: 'best-practices-trust-safety',
        },
        {
          id: 'clickjacking-mitigation',
          weight: 3,
          group: 'best-practices-trust-safety',
        },
        {
          id: 'trusted-types-xss',
          weight: 3,
          group: 'best-practices-trust-safety',
        },
        {
          id: 'script-treemap-data',
          weight: 2,
          group: 'best-practices-performance',
        },
      ],
    },

    seo: {
      title: 'SEO',
      description:
        'These checks ensure that your page is optimized for search engine results ranking.',
      auditRefs: [
        { id: 'document-title', weight: 10, group: 'seo-content' },
        { id: 'meta-description', weight: 10, group: 'seo-content' },
        { id: 'link-text', weight: 8, group: 'seo-content' },
        { id: 'image-alt', weight: 8, group: 'seo-content' },
        { id: 'crawlable-anchors', weight: 7, group: 'seo-crawl' },
        { id: 'is-crawlable', weight: 7, group: 'seo-crawl' },
        { id: 'robots-txt', weight: 7, group: 'seo-crawl' },
        { id: 'hreflang', weight: 6, group: 'seo-content' },
        { id: 'canonical', weight: 6, group: 'seo-content' },
        { id: 'structured-data', weight: 6, group: 'seo-content' },
        { id: 'http-status-code', weight: 5, group: 'seo-crawl' },
        { id: 'font-size', weight: 5, group: 'seo-content' },
        { id: 'bf-cache', weight: 4, group: 'seo-crawl' },
        { id: 'cache-insight', weight: 3, group: 'seo-crawl' },
        { id: 'cls-culprits-insight', weight: 2, group: 'seo-crawl' },
        { id: 'document-latency-insight', weight: 2, group: 'seo-crawl' },
        { id: 'dom-size-insight', weight: 2, group: 'seo-crawl' },
        { id: 'duplicated-javascript-insight', weight: 2, group: 'seo-crawl' },
        { id: 'font-display-insight', weight: 2, group: 'seo-crawl' },
        { id: 'forced-reflow-insight', weight: 2, group: 'seo-crawl' },
        { id: 'image-delivery-insight', weight: 2, group: 'seo-crawl' },
        { id: 'inp-breakdown-insight', weight: 2, group: 'seo-crawl' },
        { id: 'lcp-breakdown-insight', weight: 2, group: 'seo-crawl' },
        { id: 'lcp-discovery-insight', weight: 2, group: 'seo-crawl' },
        { id: 'legacy-javascript-insight', weight: 2, group: 'seo-crawl' },
        { id: 'modern-http-insight', weight: 2, group: 'seo-crawl' },
        {
          id: 'network-dependency-tree-insight',
          weight: 2,
          group: 'seo-crawl',
        },
        { id: 'render-blocking-insight', weight: 2, group: 'seo-crawl' },
        { id: 'third-parties-insight', weight: 2, group: 'seo-crawl' },
        { id: 'viewport-insight', weight: 2, group: 'seo-crawl' },
      ],
    },
  },
}
