import { Icon } from '../components/icons'
import { lazyRoute } from './lazy'
import { RouteIds } from './routes.constants'
import type { RouteItem } from './routes.types'

const userIcon = <Icon name='user' />
const employeeIcon = <Icon name='user' />
const categoryIcon = <Icon name='tag' />
const alertIcon = <Icon name='exclamation-triangle' />
const homeIcon = <Icon name='home' />

export const appRoutes: RouteItem[] = [
  {
    id: RouteIds.DASHBOARD,
    name: 'Dashboard',
    title: 'Dashboard',
    icon: homeIcon,
    component: lazyRoute('dashboard', 'default'),
    path: '/',
    hideSidebar: false,
    children: [],
  },
  {
    id: RouteIds.CLIENT,
    name: 'Clientes',
    title: 'Gestión de Clientes',
    icon: userIcon,
    component: lazyRoute('client-page', 'default'),
    path: '/clients',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.CLIENT_FORM_NEW,
        name: 'Nuevo Cliente',
        title: 'Crear Nuevo Cliente',
        icon: userIcon,
        component: lazyRoute('client-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CLIENT_FORM_EDIT,
        name: 'Editar Cliente',
        title: 'Editar Cliente',
        icon: userIcon,
        component: lazyRoute('client-form', 'default'),
        path: '/form/:clientId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CLIENT_DETAIL,
        name: 'Detalle Cliente',
        title: 'Detalle del Cliente',
        icon: userIcon,
        component: lazyRoute('client-detail', 'default'),
        path: '/:clientId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.EMPLOYEES,
    name: 'Empleados',
    title: 'Gestión de Empleados',
    icon: employeeIcon,
    component: lazyRoute('employee-page', 'default'),
    path: '/employees',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.EMPLOYEE_FORM_NEW,
        name: 'Nuevo Empleado',
        title: 'Crear Nuevo Empleado',
        icon: userIcon,
        component: lazyRoute('employee-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.EMPLOYEE_FORM_EDIT,
        name: 'Editar Empleado',
        title: 'Editar Empleado',
        icon: userIcon,
        component: lazyRoute('employee-form', 'default'),
        path: '/form/:employeeId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.EMPLOYEE_DETAIL,
        name: 'Detalle Empleado',
        title: 'Detalle del Empleado',
        icon: userIcon,
        component: lazyRoute('employee-detail', 'default'),
        path: '/:employeeId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.CATEGORIES,
    name: 'Categorías',
    title: 'Gestión de Categorías',
    icon: categoryIcon,
    component: lazyRoute('category-page', 'default'),
    path: '/categories',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.CATEGORY_FORM_NEW,
        name: 'Nueva Categoría',
        title: 'Crear Nueva Categoría',
        icon: categoryIcon,
        component: lazyRoute('category-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CATEGORY_FORM_EDIT,
        name: 'Editar Categoría',
        title: 'Editar Categoría',
        icon: categoryIcon,
        component: lazyRoute('category-form', 'default'),
        path: '/form/:categoryId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CATEGORY_DETAIL,
        name: 'Detalle Categoría',
        title: 'Detalle de la Categoría',
        icon: categoryIcon,
        component: lazyRoute('category-detail', 'default'),
        path: '/:categoryId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.NOT_FOUND,
    name: '404',
    title: 'Página No Encontrada',
    icon: alertIcon,
    component: lazyRoute('not-found', 'default'),
    path: '/404',
    hideSidebar: true,
    children: [],
  },
]
