import { Icon } from '../components/icons'
import { lazyRoute } from './lazy'
import { RouteIds } from './routes.constants'
import type { RouteItem } from './routes.types'

const userIcon = <Icon name='user' />
const employeeIcon = <Icon name='user' />
const categoryIcon = <Icon name='tag' />
const activityIcon = <Icon name='briefcase' />
const productIcon = <Icon name='box' />
const stockIcon = <Icon name='boxes-stacked' />
const invoiceIcon = <Icon name='file-invoice-dollar' />
const alertIcon = <Icon name='exclamation-triangle' />
const homeIcon = <Icon name='home' />

export const appRoutes: RouteItem[] = [
  {
    id: RouteIds.INVOICES,
    name: 'Facturas',
    title: 'Gestión de Facturas',
    icon: invoiceIcon,
    component: lazyRoute('invoice-page', 'default'),
    path: '/invoices',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.INVOICE_FORM_NEW,
        name: 'Nueva Factura',
        title: 'Crear Nueva Factura',
        icon: invoiceIcon,
        component: lazyRoute('invoice-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.INVOICE_FORM_EDIT,
        name: 'Editar Factura',
        title: 'Editar Factura',
        icon: invoiceIcon,
        component: lazyRoute('invoice-form', 'default'),
        path: '/form/:invoiceId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.INVOICE_DETAIL,
        name: 'Detalle Factura',
        title: 'Detalle de la Factura',
        icon: invoiceIcon,
        component: lazyRoute('invoice-detail', 'default'),
        path: '/:invoiceId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.DASHBOARD,
    name: 'Dashboard',
    title: 'Dashboard',
    icon: homeIcon,
    component: lazyRoute('dashboard', 'default'),
    path: '/',
    hideSidebar: false,
    children: [],
  },
  {
    id: RouteIds.CLIENT,
    name: 'Clientes',
    title: 'Gestión de Clientes',
    icon: userIcon,
    component: lazyRoute('client-page', 'default'),
    path: '/clients',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.CLIENT_FORM_NEW,
        name: 'Nuevo Cliente',
        title: 'Crear Nuevo Cliente',
        icon: userIcon,
        component: lazyRoute('client-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CLIENT_FORM_EDIT,
        name: 'Editar Cliente',
        title: 'Editar Cliente',
        icon: userIcon,
        component: lazyRoute('client-form', 'default'),
        path: '/form/:clientId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CLIENT_DETAIL,
        name: 'Detalle Cliente',
        title: 'Detalle del Cliente',
        icon: userIcon,
        component: lazyRoute('client-detail', 'default'),
        path: '/:clientId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CLIENT_INVOICES,
        name: 'Facturas del Cliente',
        title: 'Facturas del Cliente',
        icon: invoiceIcon,
        component: lazyRoute('client-invoices', 'default'),
        path: '/:clientId/invoices',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.EMPLOYEES,
    name: 'Empleados',
    title: 'Gestión de Empleados',
    icon: employeeIcon,
    component: lazyRoute('employee-page', 'default'),
    path: '/employees',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.EMPLOYEE_FORM_NEW,
        name: 'Nuevo Empleado',
        title: 'Crear Nuevo Empleado',
        icon: userIcon,
        component: lazyRoute('employee-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.EMPLOYEE_FORM_EDIT,
        name: 'Editar Empleado',
        title: 'Editar Empleado',
        icon: userIcon,
        component: lazyRoute('employee-form', 'default'),
        path: '/form/:employeeId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.EMPLOYEE_DETAIL,
        name: 'Detalle Empleado',
        title: 'Detalle del Empleado',
        icon: userIcon,
        component: lazyRoute('employee-detail', 'default'),
        path: '/:employeeId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.EMPLOYEE_SERVICE_HISTORY,
        name: 'Historial de Servicios',
        title: 'Historial de Servicios por Empleado',
        icon: activityIcon,
        component: lazyRoute('employee-service-history', 'default'),
        path: '/:employeeId/history',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.CATEGORIES,
    name: 'Categorías',
    title: 'Gestión de Categorías',
    icon: categoryIcon,
    component: lazyRoute('category-page', 'default'),
    path: '/categories',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.CATEGORY_FORM_NEW,
        name: 'Nueva Categoría',
        title: 'Crear Nueva Categoría',
        icon: categoryIcon,
        component: lazyRoute('category-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CATEGORY_FORM_EDIT,
        name: 'Editar Categoría',
        title: 'Editar Categoría',
        icon: categoryIcon,
        component: lazyRoute('category-form', 'default'),
        path: '/form/:categoryId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.CATEGORY_DETAIL,
        name: 'Detalle Categoría',
        title: 'Detalle de la Categoría',
        icon: categoryIcon,
        component: lazyRoute('category-detail', 'default'),
        path: '/:categoryId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.ACTIVITIES,
    name: 'Actividades',
    title: 'Gestión de Actividades',
    icon: activityIcon,
    component: lazyRoute('activity-page', 'default'),
    path: '/activities',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.ACTIVITY_FORM_NEW,
        name: 'Nueva Actividad',
        title: 'Crear Nueva Actividad',
        icon: activityIcon,
        component: lazyRoute('activity-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.ACTIVITY_FORM_EDIT,
        name: 'Editar Actividad',
        title: 'Editar Actividad',
        icon: activityIcon,
        component: lazyRoute('activity-form', 'default'),
        path: '/form/:activityId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.ACTIVITY_DETAIL,
        name: 'Detalle Actividad',
        title: 'Detalle de la Actividad',
        icon: activityIcon,
        component: lazyRoute('activity-detail', 'default'),
        path: '/:activityId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.STOCK,
    name: 'Stock',
    title: 'Gestión de Stock',
    icon: stockIcon,
    component: lazyRoute('stock', 'default'),
    path: '/stock',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.STOCK_MOVEMENTS,
        name: 'Movimientos por Producto',
        title: 'Movimientos por Producto',
        icon: stockIcon,
        component: lazyRoute('stock-movements', 'default'),
        path: '/:productId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.PRODUCTS,
    name: 'Productos',
    title: 'Gestión de Productos',
    icon: productIcon,
    component: lazyRoute('product-page', 'default'),
    path: '/products',
    hideSidebar: false,
    children: [
      {
        id: RouteIds.PRODUCT_FORM_NEW,
        name: 'Nuevo Producto',
        title: 'Crear Nuevo Producto',
        icon: productIcon,
        component: lazyRoute('product-form', 'default'),
        path: '/form/new',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.PRODUCT_FORM_EDIT,
        name: 'Editar Producto',
        title: 'Editar Producto',
        icon: productIcon,
        component: lazyRoute('product-form', 'default'),
        path: '/form/:productId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
      {
        id: RouteIds.PRODUCT_DETAIL,
        name: 'Detalle Producto',
        title: 'Detalle del Producto',
        icon: productIcon,
        component: lazyRoute('product-detail', 'default'),
        path: '/:productId',
        inheritPath: true,
        hideSidebar: true,
        children: [],
      },
    ],
  },
  {
    id: RouteIds.NOT_FOUND,
    name: '404',
    title: 'Página No Encontrada',
    icon: alertIcon,
    component: lazyRoute('not-found', 'default'),
    path: '/404',
    hideSidebar: true,
    children: [],
  },
]
