// Enum para los IDs de rutas - facilita el uso y previene errores de tipeo
export const RouteIds = {
  DASHBOARD: 'dashboard',
  CLIENT: 'client',
  CLIENT_FORM_NEW: 'client-form-new',
  CLIENT_DETAIL: 'client-detail',
  CLIENT_FORM_EDIT: 'client-form-edit',
  EMPLOYEES: 'employees',
  EMPLOYEE_FORM_NEW: 'employee-form-new',
  EMPLOYEE_DETAIL: 'employee-detail',
  EMPLOYEE_FORM_EDIT: 'employee-form-edit',
  CATEGORIES: 'categories',
  CATEGORY_FORM_NEW: 'category-form-new',
  CATEGORY_DETAIL: 'category-detail',
  CATEGORY_FORM_EDIT: 'category-form-edit',
  ACTIVITIES: 'activities',
  ACTIVITY_FORM_NEW: 'activity-form-new',
  ACTIVITY_DETAIL: 'activity-detail',
  ACTIVITY_FORM_EDIT: 'activity-form-edit',
  PRODUCTS: 'products',
  PRODUCT_FORM_NEW: 'product-form-new',
  PRODUCT_DETAIL: 'product-detail',
  PRODUCT_FORM_EDIT: 'product-form-edit',
  INVOICES: 'invoices',
  INVOICE_FORM_NEW: 'invoice-form-new',
  INVOICE_DETAIL: 'invoice-detail',
  INVOICE_FORM_EDIT: 'invoice-form-edit',
  STOCK: 'stock',
  STOCK_MOVEMENTS: 'stock-movements',
  NOT_FOUND: 'not-found',
} as const

export type RouteId = (typeof RouteIds)[keyof typeof RouteIds]
